"""v3 store connectors and printer network

Revision ID: 23147117d5c9
Revises: 9c8389979779
Create Date: 2026-04-24 13:37:36.018231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23147117d5c9'
down_revision: Union[str, None] = '9c8389979779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('auth_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('store_connection',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('credentials_json', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_store_link',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('store_connection_id', sa.UUID(), nullable=False),
    sa.Column('external_product_id', sa.String(length=200), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['store_connection_id'], ['store_connection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_connection_id', 'external_product_id', name='uq_store_external_product')
    )
    op.add_column('print_job', sa.Column('routed_by', sa.String(length=10), nullable=False))
    op.add_column('printer', sa.Column('operator_id', sa.UUID(), nullable=True))
    op.add_column('printer', sa.Column('connection_type', sa.String(length=10), nullable=False))
    op.add_column('printer', sa.Column('endpoint_url', sa.Text(), nullable=True))
    op.add_column('printer', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.add_column('printer', sa.Column('capabilities_json', sa.JSON(), nullable=True))
    op.add_column('printer', sa.Column('location_label', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'printer', 'operator', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printer', type_='foreignkey')
    op.drop_column('printer', 'location_label')
    op.drop_column('printer', 'capabilities_json')
    op.drop_column('printer', 'api_key_hash')
    op.drop_column('printer', 'endpoint_url')
    op.drop_column('printer', 'connection_type')
    op.drop_column('printer', 'operator_id')
    op.drop_column('print_job', 'routed_by')
    op.drop_table('listing_store_link')
    op.drop_table('store_connection')
    op.drop_table('operator')
    # ### end Alembic commands ###
