"""v5 performance indexes

Revision ID: 2ca53dd7cd6a
Revises: 23147117d5c9
Create Date: 2026-04-24 14:12:06.775672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca53dd7cd6a'
down_revision: Union[str, None] = '23147117d5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_opp_deleted_score', 'opportunity', ['deleted_at', 'score'], unique=False)
    op.create_index('ix_opp_deleted_status', 'opportunity', ['deleted_at', 'status'], unique=False)
    op.create_index(op.f('ix_opportunity_concept'), 'opportunity', ['concept'], unique=False)
    op.create_index(op.f('ix_opportunity_status'), 'opportunity', ['status'], unique=False)
    op.create_index(op.f('ix_trend_signal_captured_at'), 'trend_signal', ['captured_at'], unique=False)
    op.create_index(op.f('ix_trend_signal_source'), 'trend_signal', ['source'], unique=False)
    op.create_index('ix_trend_source_captured', 'trend_signal', ['source', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trend_source_captured', table_name='trend_signal')
    op.drop_index(op.f('ix_trend_signal_source'), table_name='trend_signal')
    op.drop_index(op.f('ix_trend_signal_captured_at'), table_name='trend_signal')
    op.drop_index(op.f('ix_opportunity_status'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_concept'), table_name='opportunity')
    op.drop_index('ix_opp_deleted_status', table_name='opportunity')
    op.drop_index('ix_opp_deleted_score', table_name='opportunity')
    # ### end Alembic commands ###
